# create a deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assetz-backend
  namespace: assetz-ns
spec:
  selector:
    matchLabels:
      app: assetz-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: assetz-backend
    spec:
      containers:
      - name: assetz-backend
        image: 192.168.0.112:32000/assetz/backend:latest
        ports:
        - containerPort: 8080

---
# create a service
apiVersion: v1
kind: Service
metadata:
  name: assetz-backend
  namespace: assetz-ns
  labels:
    app: assetz-backend
spec:
  type: NodePort
  selector:
    app: assetz-backend
  ports:
  - port: 8080
    nodePort: 30707
    protocol: TCP

